# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oasdiff < Formula
  desc ""
  homepage "https://github.com/oasdiff/oasdiff"
  version "2.2.0-openapi31.beta.3"

  on_macos do
    url "https://github.com/oasdiff/oasdiff/releases/download/v2.2.0-openapi31.beta.3/oasdiff_2.2.0-openapi31.beta.3_darwin_all.tar.gz"
    sha256 "e0857e34a2a7e89bb8f087976ab86bc143cae66bc907118246f3f01bb4a2018d"

    define_method(:install) do
      bin.install "oasdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v2.2.0-openapi31.beta.3/oasdiff_2.2.0-openapi31.beta.3_linux_amd64.tar.gz"
      sha256 "1d271ddd99c1b4737adf2f41ec3abb0bb3d5c95b46e94244417fa25a28754577"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v2.2.0-openapi31.beta.3/oasdiff_2.2.0-openapi31.beta.3_linux_arm64.tar.gz"
      sha256 "225ef574a8000184577773d86ca4f64a776ad290138b54e3a0a896597fef2c3a"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
  end
end
