# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oasdiff < Formula
  desc ""
  homepage "https://github.com/oasdiff/oasdiff"
  version "1.17.0"

  on_macos do
    url "https://github.com/oasdiff/oasdiff/releases/download/v1.17.0/oasdiff_1.17.0_darwin_all.tar.gz"
    sha256 "1a07d8166349aa9c2fc402a849caad86206a2747952030b6d775da945704a2e8"

    define_method(:install) do
      bin.install "oasdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v1.17.0/oasdiff_1.17.0_linux_amd64.tar.gz"
      sha256 "cddb4763e66d6012cd4e70d41c7f742eee23db30bcdc8d64ef36b183bc6c1e97"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v1.17.0/oasdiff_1.17.0_linux_arm64.tar.gz"
      sha256 "6af37f76983a8813f27d591a5b9fe4df8106fb512194831b3d7c5ed6a185312b"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
  end
end
