# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oasdiff < Formula
  desc ""
  homepage "https://github.com/oasdiff/oasdiff"
  version "1.12.6"

  on_macos do
    url "https://github.com/oasdiff/oasdiff/releases/download/v1.12.6/oasdiff_1.12.6_darwin_all.tar.gz"
    sha256 "07a3946c53f5967efdf3ffbb4bf1a29b072b0e9e94e8bdfbb358c86f632f0234"

    define_method(:install) do
      bin.install "oasdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v1.12.6/oasdiff_1.12.6_linux_amd64.tar.gz"
      sha256 "0797ba6b3502c08cf2eec00f5bae8e2ae4f31937e770084956bf08accc5b490e"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oasdiff/oasdiff/releases/download/v1.12.6/oasdiff_1.12.6_linux_arm64.tar.gz"
      sha256 "6a5f43ab381adbbaa023fade9fb82d7fa1d3dc08358dff751b7075d980c4bf80"
      define_method(:install) do
        bin.install "oasdiff"
      end
    end
  end
end
