# This file was generated by GoReleaser. DO NOT EDIT.
cask "oasdiff" do
  version "1.24.0"

  on_macos do
    sha256 "cd50458cf28e6e0b69c1cfa80000aca1ff1c2f14140fdf159c876a7294709fa4"
    url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "76f0307718c9196f44b5efc2a8b27e8a7ccde9beddd456159b8fb18377801636"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e25cc31da68afcaa345adfa1ba8cac8ef73c5578a67951755177f3830392a0fc"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oasdiff"
  desc "A diff tool for OpenAPI Specification."
  homepage "https://github.com/oasdiff/oasdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oasdiff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oasdiff"]
    end
  end

  # No zap stanza required

end
