# This file was generated by GoReleaser. DO NOT EDIT.
cask "oasdiff" do
  version "1.26.0"

  on_macos do
    sha256 "bf6d54c06a94fe54fb4fd3f85a36456b5a580119e8d441fda1235a02f981dc93"
    url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "06893108bdf5b7e310f39f0ce5aaff3151eae1ccade7ab457b16b16b6f95ae3e"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "060fd143da799b6edbe8a3befb65fd45997e79864a0ad97e67f8e10b39980b75"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oasdiff"
  desc "A diff tool for OpenAPI Specification."
  homepage "https://github.com/oasdiff/oasdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oasdiff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oasdiff"]
    end
  end

  # No zap stanza required

end
