# This file was generated by GoReleaser. DO NOT EDIT.
cask "oasdiff" do
  version "1.26.1"

  on_macos do
    sha256 "ac3f56e9b7f3c717355768bc6943b5b54461f43e5c87d1e20027e2209093d2aa"
    url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "ea0007fe536c7915785f754885d2afdb11352d6a14531950edf9d601a2baa674"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "423ef13ac4197b1fca948ccd6839dbaa8a666841b59466542f0332a7e95a1d66"
      url "https://github.com/oasdiff/oasdiff/releases/download/v#{version}/oasdiff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oasdiff"
  desc "A diff tool for OpenAPI Specification."
  homepage "https://github.com/oasdiff/oasdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oasdiff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oasdiff"]
    end
  end

  # No zap stanza required

end
